### PR TITLE
This fixes a problem with compiling the gamemode for other scripters.

### PR DESCRIPTION
**Pull request by khalidahmedshalabi**
Merge this to be able to compile the gamemode source code without errors.

### CODE REVIEW

**Comment by NoisyRico** [comment]
Sorry Man for annoying you but please I need fast answer
Tell me all steps to do this !

## please . am very sorry

lw 3andk skype aw teamspeak 2ole

**Comment by NoisyRico** [comment]
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(852) : error 017: undefined symbol "League_AutoUnpauseTimer"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(854) : error 017: undefined symbol "League_AutoUnpauseTimer"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(855) : error 017: undefined symbol "League_AutoUnpauseTimer"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(855) : warning 215: expression has no effect
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(2388) : error 017: undefined symbol "winnerid"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(2390) : error 017: undefined symbol "AddPlayerLeaguePoints"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(2394) : error 017: undefined symbol "AddPlayerLeaguePoints"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6319) : error 017: undefined symbol "LeagueMode"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : error 017: undefined symbol "PlayerShop"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : warning 215: expression has no effect
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : error 001: expected token: ";", but found "]"
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : error 029: invalid expression, assumed zero
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664          Copyright (c) 1997-2006, ITB CompuPhase

11 Errors.

**Comment by NoisyRico** [comment]
Now I have problem in progress2 !!!

**Comment by NoisyRico** [comment]
C:\Documents and Settings\Administrator\Desktop\Bulletproof-Gamemode-master\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(10) : fatal error 100: cannot read from file: "progress2"

Compilation aborted.Pawn compiler 3.2.3664          Copyright (c) 1997-2006, ITB CompuPhase

1 Error.

**Comment by khalidahmedshalabi** [comment]
@NoisyRico Looks like either you haven't downloaded the [full scripting package](https://github.com/KHKKhalid/Bulletproof-Gamemode/archive/master.zip) or you're using the wrong compiler; make sure you use (open) the compiler that you find in the [scripting package](https://github.com/KHKKhalid/Bulletproof-Gamemode/archive/master.zip).

**Comment by NoisyRico** [comment]
ok thanks ... going to try

**Comment by NoisyRico** [comment]
now I have all that Problems

D:\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(852) : error 017: undefined symbol "League_AutoUnpauseTimer"
D:\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(854) : error 017: undefined symbol "League_AutoUnpauseTimer"
D:\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(855) : error 017: undefined symbol "League_AutoUnpauseTimer"
D:\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(855) : warning 215: expression has no effect
D:\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(2388) : error 017: undefined symbol "winnerid"
D:\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(2390) : error 017: undefined symbol "AddPlayerLeaguePoints"
D:\Bulletproof-Gamemode-master\pawno\include\modules\src\match.inc(2394) : error 017: undefined symbol "AddPlayerLeaguePoints"
D:\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6319) : error 017: undefined symbol "LeagueMode"
D:\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : error 017: undefined symbol "PlayerShop"
D:\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : warning 215: expression has no effect
D:\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : error 001: expected token: ";", but found "]"
D:\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : error 029: invalid expression, assumed zero
D:\Bulletproof-Gamemode-master\gamemodes\bulletproof.pwn(6321) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664          Copyright (c) 1997-2006, ITB CompuPhase

11 Errors.

**Comment by NoisyRico** [comment]
Please answer my friend request at facebook my name is Ahmed Ayman ElKadah "3ayzk"

**Comment by NoisyRico** [comment]
Fixed Thank you I Don't how ? but Thanks for good scripts

**Pull request closed without merging**
